### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by Praskand** [tuanpmt/html5-audio-fft#1]
Please show how it works. Its stuck on loading... on both channels!
Image link is attached below.
https://user-images.githubusercontent.com/95966972/164351675-6ea65307-be6a-4f72-94c3-8658a496c99f.png

**Comment by ashleylamont** [comment]
@Praskand browser security won't let you reference files from a script to prevent JS reading content from your disk. You need to start up a local http server and point that at the directory with the audio file and html file. This is a very old example of code though, and only partially works in modern browsers. New requirements for security and usability have been added in over the years, such as requiring user input before playing audio, and several APIs being deprecated, which makes this code very flakey to run.

It does run though
<img width="450" alt="image" src="https://github.com/tuanpmt/html5-audio-fft/assets/59380148/ab0f0a2e-d3d0-487e-8717-701c93aee33c">
